platform :ios do
  desc 'Build iOS Application'
  # desc 'Fetch certificates and provisioning profiles'
  # lane :certificates do
  #   match(app_identifier: 'com.app.bundle', type: 'development', readonly: true)
  #   match(app_identifier: 'com.app.bundle', type: 'appstore', readonly: true)
  # end

  desc 'Build the iOS application.'
  private_lane :build do
    # certificates
    # increment_build_number(xcodeproj: './ios/outlierMobileApp.xcodeproj')
    gym(scheme: 'outlierMobileApp', project: './ios/outlierMobileApp.xcodeproj')
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build
    # pilot
    # commit_version_bump(message: 'Bump build', xcodeproj: './ios/name.xcodeproj')
    # push_to_git_remote
  end
end
