name: Build Android and iOS
on:
  push:
    branches:
      - feat/github-actions
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        env:
          API_HOST: ${{ secrets.API_HOST }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  # build-ios:
  #   needs: install
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Make envfile
  #       uses: SpicyPizza/create-envfile@v1
  #       with:
  #         envkey_API_HOST: ${{ secrets.API_HOST }}
  #         envkey_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  #         envkey_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
  #     - name: Install npm dependencies
  #       run: |
  #         npm install
  #     - name: Install pod dependencies
  #       run: |
  #         cd ios && pod install
  #     - name: Build app
  #       run: |
  #         xcodebuild -workspace outlierMobileApp.xcworkspace -scheme outlierMobileApp archive -archivePath outlierMobileApp.xcarchive -allowProvisioningUpdates
  #         xcodebuild -exportArchive -archivePath ./outlierMobileApp.xcarchive -exportPath . -exportOptionsPlist outlierMobileApp/Info.plist
  #         mv outlierMobileApp.ipa ../outlierMobileApp.ipa
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: outlierMobileApp.ipa
  #         path: ios/build/
