- name: Continuous Integration
- name: Checkout
  uses: actions/checkout@v2
- name: Cache dependencies
  uses: actions/cache@v2
  with:
    path: ~/.npm
    key: npm-${{ hashFiles('package-lock.json') }}
    restore-keys: npm-
  run: |
    npm install
- name: Fastlane Action
  # You may pin to the exact commit or the version.
  # uses: maierj/fastlane-action@2121d31315dd0054a407c2c24938ae1fa29b883d
  uses: maierj/fastlane-action@v2.0.1
  with:
    # The lane that should be executed.
    lane: prodBuild
    # The relative path from the project root directory to the subdirectory where the fastlane folder is located.
    subdirectory: ./android
    # The directory where Ruby gems should be installed to and cached. If a relative path is specified, it's applied relative to the location of the Gemfile, which is either the project root or the directory from the `subdirectory` parameter.
    bundle-install-path: ./android
    # The action tracks usage in Firebase by default. You can disable tracking by setting this parameter to 'true'.
    skip-tracking: true
    # The options that should be passed as arguments to the lane. The options should be serialized as a JSON object.
    # options: # optional
