name: Version increment

on:
  pull_request:
    types: [closed]

jobs:
  job_01:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Version Control on PR merge
        run: .github/workflows/read_commit.sh
