name: Version increment

on:
  pull_request:
    types: [closed]

jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: Version Control on PR merge
        run: |
          chmod +x ".github/script.sh"
          "${GITHUB_WORKSPACE}/.github/script.sh"
        shell: bash
