name: Version increment

on:
  pull_request:
    types: [closed]

jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: Version Control on PR merge
        run: npm version patch

        #   |
        #   chmod +x ./.github/workflows/read_commit.sh
        # shell: bash
