name: Version increment

on:
  pull_request:
    types: [closed]

jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version Control on PR merge
        run: |
          pwd
          ls
          # chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"
          # "${GITHUB_WORKSPACE}/.github/script.sh"
        shell: bash
