name: Version increment

on:
  pull_request:
    types: [closed]

jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version Control on PR merge
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"
          git config --global user.email "githubaction@outlier.org"
          git config --global user.name "Github CI/CD"
          "${GITHUB_WORKSPACE}/.github/script.sh"
          git branch
          git remote -v
        shell: bash
