name: Version increment

on:
  pull_request:
    types: [open]

jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: Version Control on PR merge
        run: |
          echo pwd
          echo ls
          chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"
          "${GITHUB_WORKSPACE}/.github/script.sh"
        shell: bash
